name:                suntimes
version:             0.1.0.0
github:              "githubuser/suntimes"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/suntimes#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - exceptions
  - http-client
  - monad-logger
  - mtl
  - req
  - text
  - time
  - transformers
  default-extensions:
  - DeriveGeneric
  - DeriveAnyClass
  - GeneralizedNewtypeDeriving
  - OverloadedStrings
  - RecordWildCards
  - TemplateHaskell

executables:
  suntimes-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - bytestring
    - exceptions
    - mtl
    - optparse-applicative
    - suntimes
    - text
    - transformers
    default-extensions:
    - GeneralizedNewtypeDeriving

tests:
  suntimes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - suntimes
