name:                iplookup
version:             0.1.0.0
github:              "githubuser/iplookup"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/iplookup#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - exceptions
  - extra
  - hedgehog
  - text
  default-extensions:
  - DeriveAnyClass
  - OverloadedStrings
  - TypeApplications

executables:
  iplookup-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exceptions
    - iplookup
    - optparse-applicative

tests:
  iplookup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filepath
    - hedgehog
    - iplookup
    - tasty
    - tasty-golden
    - tasty-hedgehog
    - tasty-hspec
  iplookup-doctests:
    main:                Doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - doctest

benchmarks:
  iplookup-bench:
    source-dirs: benchmarks
    main: Bench.hs
    dependencies:
      - iplookup
      - criterion >= 1.4 && < 1.6
      - deepseq >= 1.3 && <1.5

data-files:
  - data/*.*
  - data/benchmarks/*.*  
