name:                du
version:             0.1.0.0
github:              "githubuser/du"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/du#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - mtl
  - filepath
  - directory
  - unix-compat
  - extra
  - text
  - text-show
  default-extensions:
  - RecordWildCards
  - NamedFieldPuns
  - OverloadedStrings
  - GeneralizedNewtypeDeriving

executables:
  du-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - du
    - text
    - text-show
    - optparse-applicative
    default-extensions:
    - RecordWildCards
    - NamedFieldPuns
    - OverloadedStrings

tests:
  du-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - du
